name: 'Yarn build'
description: 'Setup node and yarn, then runs yarn install and yarn build'
inputs:
  node-version:
    description: 'Node version'
    required: false
    default: 14.x
  user:
    description: 'Repository User'
    required: true
  password:
    description: 'Repository Password'
    required: true
runs:
  using: "composite"
    steps:
    - name: Setup yarn with node ${{ inputs.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    - run: npm install --global yarn
    
    - name: Yarn install
      run: yarn install
      
    - name: Yarn build
      run: yarn build
